# Accessing Data within Pandas - Lab

## Introduction

In this lab, we'll look at a dataset which contains information on World Cup matches. Let's use the Pandas commands learned in the previous lesson to learn more about our data!

## Objectives
You will be able to: 
- Use pandas methods and attributes to access information about a dataset 
- Index pandas dataframes with .loc, .iloc, and column names 
- Use a boolean mask to index pandas series and dataframes

## Load the data

Load the file `'WorldCupMatches.csv'` as a DataFrame in Pandas.

In [14]:
# Import pandas using the standard alias
import pandas as pd

# Import 'WorldCupMatches.csv' as a DataFrame
df = pd.read_csv('WorldCupMatches.csv')
df

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,Attendance,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials
0,1930,13 Jul 1930 - 15:00,Group 1,Pocitos,Montevideo,France,4,1,Mexico,,4444.0,3,0,LOMBARDI Domingo (URU),CRISTOPHE Henry (BEL),REGO Gilberto (BRA),201,1096,FRA,MEX
1,1930,13 Jul 1930 - 15:00,Group 4,Parque Central,Montevideo,USA,3,0,Belgium,,18346.0,2,0,MACIAS Jose (ARG),MATEUCCI Francisco (URU),WARNKEN Alberto (CHI),201,1090,USA,BEL
2,1930,14 Jul 1930 - 12:45,Group 2,Parque Central,Montevideo,Yugoslavia,2,1,Brazil,,24059.0,2,0,TEJADA Anibal (URU),VALLARINO Ricardo (URU),BALWAY Thomas (FRA),201,1093,YUG,BRA
3,1930,14 Jul 1930 - 14:50,Group 3,Pocitos,Montevideo,Romania,3,1,Peru,,2549.0,1,0,WARNKEN Alberto (CHI),LANGENUS Jean (BEL),MATEUCCI Francisco (URU),201,1098,ROU,PER
4,1930,15 Jul 1930 - 16:00,Group 1,Parque Central,Montevideo,Argentina,1,0,France,,23409.0,0,0,REGO Gilberto (BRA),SAUCEDO Ulises (BOL),RADULESCU Constantin (ROU),201,1085,ARG,FRA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
847,2014,05 Jul 2014 - 17:00,Quarter-finals,Arena Fonte Nova,Salvador,Netherlands,0,0,Costa Rica,Netherlands win on penalties (4 - 3),51179.0,0,0,Ravshan IRMATOV (UZB),RASULOV Abduxamidullo (UZB),KOCHKAROV Bakhadyr (KGZ),255953,300186488,NED,CRC
848,2014,08 Jul 2014 - 17:00,Semi-finals,Estadio Mineirao,Belo Horizonte,Brazil,1,7,Germany,,58141.0,0,5,RODRIGUEZ Marco (MEX),TORRENTERA Marvin (MEX),QUINTERO Marcos (MEX),255955,300186474,BRA,GER
849,2014,09 Jul 2014 - 17:00,Semi-finals,Arena de Sao Paulo,Sao Paulo,Netherlands,0,0,Argentina,Argentina win on penalties (2 - 4),63267.0,0,0,C�neyt �AKIR (TUR),DURAN Bahattin (TUR),ONGUN Tarik (TUR),255955,300186490,NED,ARG
850,2014,12 Jul 2014 - 17:00,Play-off for third place,Estadio Nacional,Brasilia,Brazil,0,3,Netherlands,,68034.0,0,2,HAIMOUDI Djamel (ALG),ACHIK Redouane (MAR),ETCHIALI Abdelhak (ALG),255957,300186502,BRA,NED
851,2014,13 Jul 2014 - 16:00,Final,Estadio do Maracana,Rio De Janeiro,Germany,1,0,Argentina,Germany win after extra time,74738.0,0,0,Nicola RIZZOLI (ITA),Renato FAVERANI (ITA),Andrea STEFANI (ITA),255959,300186501,GER,ARG

## Common methods and attributes

Use the correct method to look at the first 7 rows of the dataset.

In [15]:
# Print the first 7 rows of df
df.iloc[:7]

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,Attendance,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials
0,1930,13 Jul 1930 - 15:00,Group 1,Pocitos,Montevideo,France,4,1,Mexico,,4444.0,3,0,LOMBARDI Domingo (URU),CRISTOPHE Henry (BEL),REGO Gilberto (BRA),201,1096,FRA,MEX
1,1930,13 Jul 1930 - 15:00,Group 4,Parque Central,Montevideo,USA,3,0,Belgium,,18346.0,2,0,MACIAS Jose (ARG),MATEUCCI Francisco (URU),WARNKEN Alberto (CHI),201,1090,USA,BEL
2,1930,14 Jul 1930 - 12:45,Group 2,Parque Central,Montevideo,Yugoslavia,2,1,Brazil,,24059.0,2,0,TEJADA Anibal (URU),VALLARINO Ricardo (URU),BALWAY Thomas (FRA),201,1093,YUG,BRA
3,1930,14 Jul 1930 - 14:50,Group 3,Pocitos,Montevideo,Romania,3,1,Peru,,2549.0,1,0,WARNKEN Alberto (CHI),LANGENUS Jean (BEL),MATEUCCI Francisco (URU),201,1098,ROU,PER
4,1930,15 Jul 1930 - 16:00,Group 1,Parque Central,Montevideo,Argentina,1,0,France,,23409.0,0,0,REGO Gilberto (BRA),SAUCEDO Ulises (BOL),RADULESCU Constantin (ROU),201,1085,ARG,FRA
5,1930,16 Jul 1930 - 14:45,Group 1,Parque Central,Montevideo,Chile,3,0,Mexico,,9249.0,1,0,CRISTOPHE Henry (BEL),APHESTEGUY Martin (URU),LANGENUS Jean (BEL),201,1095,CHI,MEX
6,1930,17 Jul 1930 - 12:45,Group 2,Parque Central,Montevideo,Yugoslavia,4,0,Bolivia,,18306.0,0,0,MATEUCCI Francisco (URU),LOMBARDI Domingo (URU),WARNKEN Alberto (CHI),201,1092,YUG,BOL

Look at the last 3 rows of the data set.

In [16]:
# Print the last 3 rows of df
df.iloc[-3:]

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,Attendance,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials
849,2014,09 Jul 2014 - 17:00,Semi-finals,Arena de Sao Paulo,Sao Paulo,Netherlands,0,0,Argentina,Argentina win on penalties (2 - 4),63267.0,0,0,C�neyt �AKIR (TUR),DURAN Bahattin (TUR),ONGUN Tarik (TUR),255955,300186490,NED,ARG
850,2014,12 Jul 2014 - 17:00,Play-off for third place,Estadio Nacional,Brasilia,Brazil,0,3,Netherlands,,68034.0,0,2,HAIMOUDI Djamel (ALG),ACHIK Redouane (MAR),ETCHIALI Abdelhak (ALG),255957,300186502,BRA,NED
851,2014,13 Jul 2014 - 16:00,Final,Estadio do Maracana,Rio De Janeiro,Germany,1,0,Argentina,Germany win after extra time,74738.0,0,0,Nicola RIZZOLI (ITA),Renato FAVERANI (ITA),Andrea STEFANI (ITA),255959,300186501,GER,ARG

Get a concise summary of the data using `.info()`.

In [17]:
# Print a concise summary of df
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 852 entries, 0 to 851
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Year                  852 non-null    int64
 1   Datetime              852 non-null    object
 2   Stage                 852 non-null    object
 3   Stadium               852 non-null    object
 4   City                  852 non-null    object
 5   Home Team Name        852 non-null    object
 6   Home Team Goals       852 non-null    int64
 7   Away Team Goals       852 non-null    int64
 8   Away Team Name        852 non-null    object
 9   Win conditions        852 non-null    object
 10  Attendance            850 non-null    float64
 11  Half-time Home Goals  852 non-null    int64
 12  Half-time Away Goals  852 non-null    int64
 13  Referee               852 non-null    object
 14  Assistant 1           852 non-null    object
 15  Assistant 2           852 non-null    object
 16  RoundID               852 non-null    int64
 17  MatchID               852 non-null    int64
 18  Home Team Initials    852 non-null    object
 19  Away Team Initials    852 non-null    object
dtypes: float64(1), int64(7), object(12)
memory usage: 133.2+ KB

Obtain a tuple representing the number of rows and number of columns

In [18]:
# Print the number of rows and columns in df
df.shape

(852, 20)

Use the appropriate attribute to get the column names

In [19]:
# Print the column names of df
df.columns

Index(['Year', 'Datetime', 'Stage', 'Stadium', 'City', 'Home Team Name',
       'Home Team Goals', 'Away Team Goals', 'Away Team Name',
       'Win conditions', 'Attendance', 'Half-time Home Goals',
       'Half-time Away Goals', 'Referee', 'Assistant 1', 'Assistant 2',
       'RoundID', 'MatchID', 'Home Team Initials', 'Away Team Initials'],
      dtype='object')

## Selecting DataFrame information

When looking at the DataFrame's `.head()`, you might have noticed that the games are structured chronologically in the DataFrame.

Use the right selection method to print all the information from the 3rd to the 5th game.

In [20]:
# Print rows 3 through 5
df.iloc[3:6]

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,Attendance,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials
3,1930,14 Jul 1930 - 14:50,Group 3,Pocitos,Montevideo,Romania,3,1,Peru,,2549.0,1,0,WARNKEN Alberto (CHI),LANGENUS Jean (BEL),MATEUCCI Francisco (URU),201,1098,ROU,PER
4,1930,15 Jul 1930 - 16:00,Group 1,Parque Central,Montevideo,Argentina,1,0,France,,23409.0,0,0,REGO Gilberto (BRA),SAUCEDO Ulises (BOL),RADULESCU Constantin (ROU),201,1085,ARG,FRA
5,1930,16 Jul 1930 - 14:45,Group 1,Parque Central,Montevideo,Chile,3,0,Mexico,,9249.0,1,0,CRISTOPHE Henry (BEL),APHESTEGUY Martin (URU),LANGENUS Jean (BEL),201,1095,CHI,MEX

Now, print all the info from game 5-9, but we're only interested in printing out the, "Home Team Name" and the, "Away Team Name."

In [22]:
# Print rows 5 through 9 and columns 'Home Team Name' and 'Away Team Name'
df.loc[5:9, ["Home Team Name","Away Team Name"]]

  Home Team Name Away Team Name
5          Chile         Mexico
6     Yugoslavia        Bolivia
7            USA       Paraguay
8        Uruguay           Peru
9          Chile         France

Next, we'd like the information on all the games played in Group 3 for the 1950 World Cup.

In [55]:
# Print all info for games played in 1950 for Group 3
import operator

# df.loc[lambda v: operator.and_(v['Year'] == int(1950), v['Stage'] == "Group 3") ]


df.loc[(df['Year'] == int(1950)) & (df['Stage'] == "Group 3") ]

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,Attendance,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials
56,1950,25 Jun 1950 - 15:00,Group 3,Pacaembu,Sao Paulo,Sweden,3,2,Italy,,36502.0,2,1,LUTZ Jean (SUI),BERANEK Alois (AUT),TEJADA Carlos (MEX),208,1219,SWE,ITA
61,1950,29 Jun 1950 - 15:30,Group 3,Durival de Brito,Curitiba,Sweden,2,2,Paraguay,,7903.0,2,1,MITCHELL Robert (SCO),LEMESIC Leo (YUG),GARCIA Prudencio (USA),208,1228,SWE,PAR
65,1950,02 Jul 1950 - 15:00,Group 3,Pacaembu,Sao Paulo,Italy,2,0,Paraguay,,25811.0,1,0,ELLIS Arthur (ENG),GARCIA Prudencio (USA),DE LA SALLE Charles (FRA),208,1218,ITA,PAR

Let's repeat the command above, but now we only want to print out the attendance column for the Group 3 games.

You can combine conditions like this:

`df[(condition1) | (condition2)]`  -> Returns rows where either condition is true

`df[(condition1) & (condition2)]`  -> Returns rows where both conditions are true

In [56]:
# Print the 'Attendance' column for games played in 1950 for Group 3
df.loc[(df['Year'] == int(1950)) & (df['Stage'] == "Group 3"), ["Attendance"]]

    Attendance
56     36502.0
61      7903.0
65     25811.0

Throughout the entire history of the World Cup, how many home games were played by the Netherlands?

In [58]:
# Number of home games played by the Netherlands
len(df.loc[df['Home Team Initials'] == "NED"])

32

How many games were played by the Netherlands in total?

In [59]:
# Number of games played by the Netherlands in total
len(df.loc[(df['Home Team Initials'] == "NED") | (df['Away Team Initials'] == "NED")])

54

Next, let's try and figure out how many games the USA played in the 2014 World Cup.

In [62]:
# Number of games the USA played in the 2014 world cup
len(df.loc[((df['Home Team Initials'] == "USA") | (df['Away Team Initials'] == "USA")) & (df['Year'] == int(2014))])

5

Now, let's try to find out how many countries participated in the 1986 World Cup.

Hint 1: as a first step, create a new dataset that only contains games in that year.

Hint 2: You can use `.unique()` to make sure you don't end up with duplicate country names.

In [71]:
# Number of countries participated in the 1986 world cup
df86 = df.loc[df['Year'] == int(1986)]
set_df86_home = set(list(df86['Home Team Initials']))
set_df86_away = set(list(df86['Away Team Initials']))
df86_all = sorted(list(set_df86_home & set_df86_away))
num_countries_world_cup_1986 = len(df86_all)

print("num_countries_world_cup_1986 = " + repr(num_countries_world_cup_1986 ))

num_countries_world_cup_1986 = 24

In World Cup history, how many matches had 5 goals or more in total?

In [76]:
# Number of matches that had 5 or more goals in total
# print(repr(len(df.loc[(df['Home Team Goals'] + df['Away Team Goals']) >= 0])))
print(repr(len(df.loc[(df['Home Team Goals'] + df['Away Team Goals']) >= 5])))

147

## Changing values and creating new columns

With the information you currently have in your `df`, create a new column, "Half-time Goals."

In [77]:
# Create a new column 'Half-time Goals' in df
df['Half-time Goals'] = df["Half-time Home Goals"] + df["Half-time Away Goals"]

df

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,...,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials,Half-time Goals
0,1930,13 Jul 1930 - 15:00,Group 1,Pocitos,Montevideo,France,4,1,Mexico,,...,3,0,LOMBARDI Domingo (URU),CRISTOPHE Henry (BEL),REGO Gilberto (BRA),201,1096,FRA,MEX,3
1,1930,13 Jul 1930 - 15:00,Group 4,Parque Central,Montevideo,USA,3,0,Belgium,,...,2,0,MACIAS Jose (ARG),MATEUCCI Francisco (URU),WARNKEN Alberto (CHI),201,1090,USA,BEL,2
2,1930,14 Jul 1930 - 12:45,Group 2,Parque Central,Montevideo,Yugoslavia,2,1,Brazil,,...,2,0,TEJADA Anibal (URU),VALLARINO Ricardo (URU),BALWAY Thomas (FRA),201,1093,YUG,BRA,2
3,1930,14 Jul 1930 - 14:50,Group 3,Pocitos,Montevideo,Romania,3,1,Peru,,...,1,0,WARNKEN Alberto (CHI),LANGENUS Jean (BEL),MATEUCCI Francisco (URU),201,1098,ROU,PER,1
4,1930,15 Jul 1930 - 16:00,Group 1,Parque Central,Montevideo,Argentina,1,0,France,,...,0,0,REGO Gilberto (BRA),SAUCEDO Ulises (BOL),RADULESCU Constantin (ROU),201,1085,ARG,FRA,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
847,2014,05 Jul 2014 - 17:00,Quarter-finals,Arena Fonte Nova,Salvador,Netherlands,0,0,Costa Rica,Netherlands win on penalties (4 - 3),...,0,0,Ravshan IRMATOV (UZB),RASULOV Abduxamidullo (UZB),KOCHKAROV Bakhadyr (KGZ),255953,300186488,NED,CRC,0
848,2014,08 Jul 2014 - 17:00,Semi-finals,Estadio Mineirao,Belo Horizonte,Brazil,1,7,Germany,,...,0,5,RODRIGUEZ Marco (MEX),TORRENTERA Marvin (MEX),QUINTERO Marcos (MEX),255955,300186474,BRA,GER,5
849,2014,09 Jul 2014 - 17:00,Semi-finals,Arena de Sao Paulo,Sao Paulo,Netherlands,0,0,Argentina,Argentina win on penalties (2 - 4),...,0,0,C�neyt �AKIR (TUR),DURAN Bahattin (TUR),ONGUN Tarik (TUR),255955,300186490,NED,ARG,0
850,2014,12 Jul 2014 - 17:00,Play-off for third place,Estadio Nacional,Brasilia,Brazil,0,3,Netherlands,,...,0,2,HAIMOUDI Djamel (ALG),ACHIK Redouane (MAR),ETCHIALI Abdelhak (ALG),255957,300186502,BRA,NED,2
851,2014,13 Jul 2014 - 16:00,Final,Estadio do Maracana,Rio De Janeiro,Germany,1,0,Argentina,Germany win after extra time,...,0,0,Nicola RIZZOLI (ITA),Renato FAVERANI (ITA),Andrea STEFANI (ITA),255959,300186501,GER,ARG,0

Run the code below. You'll notice that for Korea, there are records for both North-Korea (Korea DPR) and South-Korea (Korea Republic).

In [78]:
# Print all records containing the string 'Korea'
df.loc[df['Home Team Name'].str.contains('Korea'), 'Home Team Name']

179         Korea DPR
187         Korea DPR
374    Korea Republic
386    Korea Republic
434    Korea Republic
444    Korea Republic
480    Korea Republic
524    Korea Republic
593    Korea Republic
609    Korea Republic
635    Korea Republic
642    Korea Republic
655    Korea Republic
710    Korea Republic
753         Korea DPR
802    Korea Republic
818    Korea Republic
Name: Home Team Name, dtype: object

Imagine that, for some reason, we simply want Korea listed as one entry, so we want to replace every "Home Team Name" and "Away Team Name" entry that contains "Korea" to simply "Korea". In the same way, we want to change the columns "Home Team Initials" and "Away Team Initials" to NSK (North & South Korea) instead of "KOR" and "PRK".

In [84]:
# Import pandas using the standard alias
import pandas as pd

# Import 'WorldCupMatches.csv' as a DataFrame
df = pd.read_csv('WorldCupMatches.csv')
df

# Print all records containing the string 'Korea'
print("ORIGINAL CASE:")
df_has_word_Korea = df.loc[
    (df['Home Team Name'].str.contains('Korea')) | (df['Away Team Name'].str.contains('Korea')), 
    ['Home Team Name', "Home Team Initials", 'Away Team Name', "Away Team Initials"]]
print("df_has_word_Korea = ")
print(df_has_word_Korea)

# Update the 'Home Team Name' and 'Home Team Initials' columns 
df["Original Home Team Name"] = df["Home Team Name"]
df["Original Away Team Name"] = df["Away Team Name"]
df["Original Home Team Initials"] = df["Home Team Initials"]
df["Original Away Team Initials"] = df["Away Team Initials"]
df.loc[df['Original Home Team Name'].str.contains('Korea'), "Home Team Name"] = "Korea"
df.loc[df['Original Away Team Name'].str.contains('Korea'), "Away Team Name"] = "Korea"
df.loc[df['Original Home Team Name'].str.contains('Korea'), "Home Team Initials"] = "NSK"
df.loc[df['Original Away Team Name'].str.contains('Korea'), "Away Team Initials"] = "NSK"

print()
print("REVISED CASE:")
df_has_word_Korea = df.loc[
    (df['Home Team Name'].str.contains('Korea')) | (df['Away Team Name'].str.contains('Korea')), 
    ['Home Team Name', "Home Team Initials", 'Away Team Name', "Away Team Initials"]]
print("df_has_word_Korea = ")
print(df_has_word_Korea)

ORIGINAL CASE:
df_has_word_Korea =
     Home Team Name Home Team Initials  Away Team Name Away Team Initials
80          Hungary                HUN  Korea Republic                KOR
88           Turkey                TUR  Korea Republic                KOR
171    Soviet Union                URS       Korea DPR                PRK
179       Korea DPR                PRK           Chile                CHI
187       Korea DPR                PRK           Italy                ITA
195        Portugal                POR       Korea DPR                PRK
364       Argentina                ARG  Korea Republic                KOR
374  Korea Republic                KOR        Bulgaria                BUL
386  Korea Republic                KOR           Italy                ITA
421         Belgium                BEL  Korea Republic                KOR
434  Korea Republic                KOR           Spain                ESP
444  Korea Republic                KOR         Uruguay                URU
464           Spain                ESP  Korea Republic                KOR
480  Korea Republic                KOR         Bolivia                BOL
490         Germany                GER  Korea Republic                KOR
524  Korea Republic                KOR          Mexico                MEX
542     Netherlands                NED  Korea Republic                KOR
556         Belgium                BEL  Korea Republic                KOR
593  Korea Republic                KOR          Poland                POL
609  Korea Republic                KOR             USA                USA
625        Portugal                POR  Korea Republic                KOR
635  Korea Republic                KOR           Italy                ITA
639           Spain                ESP  Korea Republic                KOR
640         Germany                GER  Korea Republic                KOR
642  Korea Republic                KOR          Turkey                TUR
655  Korea Republic                KOR            Togo                TOG
672          France                FRA  Korea Republic                KOR
691     Switzerland                SUI  Korea Republic                KOR
710  Korea Republic                KOR          Greece                GRE
721          Brazil                BRA       Korea DPR                PRK
725       Argentina                ARG  Korea Republic                KOR
737        Portugal                POR       Korea DPR                PRK
742         Nigeria                NGA  Korea Republic                KOR
753       Korea DPR                PRK   C�te d'Ivoire                CIV
756         Uruguay                URU  Korea Republic                KOR
788          Russia                RUS  Korea Republic                KOR
802  Korea Republic                KOR         Algeria                ALG
818  Korea Republic                KOR         Belgium                BEL

REVISED CASE:
df_has_word_Korea =
    Home Team Name Home Team Initials Away Team Name Away Team Initials
80         Hungary                HUN          Korea                NSK
88          Turkey                TUR          Korea                NSK
171   Soviet Union                URS          Korea                NSK
179          Korea                NSK          Chile                CHI
187          Korea                NSK          Italy                ITA
195       Portugal                POR          Korea                NSK
364      Argentina                ARG          Korea                NSK
374          Korea                NSK       Bulgaria                BUL
386          Korea                NSK          Italy                ITA
421        Belgium                BEL          Korea                NSK
434          Korea                NSK          Spain                ESP
444          Korea                NSK        Uruguay                URU
464          Spain                ESP          Korea                NSK
480          Korea                NSK        Bolivia                BOL
490        Germany                GER          Korea                NSK
524          Korea                NSK         Mexico                MEX
542    Netherlands                NED          Korea                NSK
556        Belgium                BEL          Korea                NSK
593          Korea                NSK         Poland                POL
609          Korea                NSK            USA                USA
625       Portugal                POR          Korea                NSK
635          Korea                NSK          Italy                ITA
639          Spain                ESP          Korea                NSK
640        Germany                GER          Korea                NSK
642          Korea                NSK         Turkey                TUR
655          Korea                NSK           Togo                TOG
672         France                FRA          Korea                NSK
691    Switzerland                SUI          Korea                NSK
710          Korea                NSK         Greece                GRE
721         Brazil                BRA          Korea                NSK
725      Argentina                ARG          Korea                NSK
737       Portugal                POR          Korea                NSK
742        Nigeria                NGA          Korea                NSK
753          Korea                NSK  C�te d'Ivoire                CIV
756        Uruguay                URU          Korea                NSK
788         Russia                RUS          Korea                NSK
802          Korea                NSK        Algeria                ALG
818          Korea                NSK        Belgium                BEL

Make sure to verify your answer!

In [85]:
# Check the updated columns
print("Yo, it all checks out.")

Yo, it all checks out.

## Summary

In this lab, you learned how to access data within Pandas!

I have spoken.  2020-08-25_1048_MDT